/**
 * Constant User Action Types
 */
export const UserActionTypes = {
    USER_REGISTER: 'USER_REGISTER',
    USER_REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    USER_LOGIN: 'USER_LOGIN',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

    USER_LOGOUT: 'USER_LOGOUT',
    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
    USER_LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE',

    USER_ALL: 'USER_ALL',
    USER_ALL_SUCCESS: 'USER_ALL_SUCCESS',
    USER_ALL_FAILURE: 'USER_ALL_FAILURE',

    USER_DELETE: 'USER_DELETE',
    USER_DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
    USER_DELETE_FAILURE: 'USER_DELETE_FAILURE'
};
